name: "update release tag"
description: "Update release tag in the GitHub repo"
author: "Aji Pramono"
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
