name: "update release tag"
description: "Update release tag in the GitHub repo"
author: "Aji Pramono"
inputs:
  tag_name:
    description: "Name of the tag to create or update"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
